---
title: "Devoir 1 - Méthodes Statistiques"
author: |
  "XXX"
date: |
  Hiver 2026
output:
  pdf_document:
    number_sections: false
header-includes:
  - \usepackage{xcolor}
  - \definecolor{matlabOrange}{RGB}{217,85,26}
  - \usepackage{titling}
  - \pretitle{\begin{center}\color{matlabOrange}\Huge}  # title color & size
  - \posttitle{\end{center}}
knitr:
  fig.width: 6
  fig.height: 4
  fig.align: "center"  
---


## Structure du Projet

### Q1. 
```{r}
library("xts")
library("zoo")
#selection de la plage janvier 2005 à dernière data
data_TP01 <- prices["2005-01-01/"]
#rendement log pour chaque indice
logr_SPX <- diff(log(data_TP01$SP500))
logr_UKX <- diff(log(data_TP01$FTSE100))
#suppression des NA (les première valeurs)
logr_SPX <- logr_SPX[!is.na(logr_SPX)]
logr_UKX <- logr_UKX[!is.na(logr_UKX)]
```
## Explications des fonctions

### Q2 
```{r}
f_forecast_var <- function(y, level) {
  ### Compute the VaR forecast of a GARCH(1,1) model with Normal errors at the desired risk level
  #  INPUTS
  #   y     : [vector] (T x 1) of observations (log-returns)
  #   level : [scalar] risk level (e.g. 0.95 for a VaR at the 95# risk level)
  #  OUTPUTS
  #   VaR   : [scalar] VaR forecast 
  #   sig2  : [vector] (T+1 x 1) conditional variances
  #   theta : [vector] GARCH parameters
  #  NOTE
  #   o the estimation is done by maximum likelihood
  
  # Fit a GARCH(1,1) model with Normal errors
  # Starting values and bounds
  theta0 <- c(0.1 * var(y), 0.1, 0.8)
  #il n'y a que theta[1] qui doit etre strictement positif les autres peuvent être 0 
  LB     <- c(1e-8,1e-8,1e-8) 
  # Stationarity condition
  A <- matrix(c(1,0,0,0,1,0,0,0,1,0,-1,-1),nrow=4, byrow=TRUE) #matrice diag & contrainte theta[2] + theta [3] inf à 1-err
  b <- c(LB[1],LB[2],LB[3],-(1-1e-5))
  # Run the optimization
  fit <- constrOptim(
  theta = theta0,
  f     = f_nll,
  y     = y,
  ui    = A,
  ci    = b, 
  grad  = NULL
  )
  theta <- fit$par
  # Recompute the conditional variance
  sig2 <- f_ht(theta, y)
  
  # Compute the next-day ahead VaR for the Normal model
  VaR <- -qnorm(1 - level) * sqrt(tail(sig2, 1)) 
  
  out <- list(VaR_Forecast = VaR, 
              ConditionalVariances = sig2, 
              GARCH_param = theta)
  
  out
}

f_nll <- function(theta, y) {
  ### Fonction which computes the negative log likelihood value 
  ### of a GARCH model with Normal errors
  #  INPUTS
  #   theta  : [vector] of parameters
  #   y      : [vector] (T x 1) of observations
  #  OUTPUTS
  #   nll    : [scalar] negative log likelihood value
  
  T <- length(y)
  
  # Compute the conditional variance of a GARCH(1,1) model
  sig2 <- f_ht(theta, y)
  
  # Consider the T values
  sig2 <- sig2[1:T]
  
  # Compute the loglikelihood
  ll <- sum(dnorm(y, mean = 0, sd = sqrt(sig2), log = TRUE))
  
  # Output the negative value
  nll <- -ll
  
  nll
}

f_ht <- function(theta, y)  {
  ### Function which computes the vector of conditional variance
  #  INPUTS
  #   x0 : [vector] (3 x 1)
  #   y     : [vector] (T x 1) log-returns
  #  OUTPUTS 
  #   sig2  : [vector] (T+1 x 1) conditional variances
  
  # Extract the parameters
  a0 <- theta[1]
  a1 <- theta[2]
  b1 <- theta[3]
  
  T <- length(y)
  
  # Initialize the conditional variances
  sig2 <- rep(NA, T + 1)
  
  # Start with unconditional variances
  sig2[1] <- a0 / (1 - a1 - b1)
  
  # Compute conditional variance at each step
  #choc d'hier*coef de réaction + persistance*coef de mémoire
  for (t in 2:(T + 1)) {
  sig2[t] <- a0 + a1 * y[t-1]^2 + b1 * sig2[t-1]
  }
  sig2
}
```
### Q3
```{r}
T <- 1000
logr_SPX_trim <- as.numeric(logr_SPX[1:T])
logr_UKX_trim <- as.numeric(logr_UKX[1:T])

res_SPX <- f_forecast_var(logr_SPX_trim, 0.95)
res_UKX <- f_forecast_var(logr_UKX_trim, 0.95)

res_SPX$VaR_Forecast
res_UKX$VaR_Forecast
#Plus grosse VaR pour le SPX à 6.942% contre 6.237% pour le UKX. 
```
**Interpretation: La plus grosse VaR est celle du SPX à 6.94% contre 6.24% pour le UKX. Cela signifie que le SPX est plus risqué que le UKX.**

### Q4
```{r}
#conversion en as.numeric pour gagner de la performance 
logr_SPX_num <- as.numeric(logr_SPX)
logr_UKX_num <- as.numeric(logr_UKX)
# Initialisation des vecteurs de VaR 
VaRSPX <- rep(NA, T)
VaRUKX <- rep(NA, T)

#Création du vecteur de rendement réalisés
# retSPX<- Return.calculate(prices = data_TP01$SP500, method = "discrete")[T:(T+T-1)]
# retUKX<- Return.calculate(prices = data_TP01$FTSE100, method = "discrete")[T:(T+T-1)]
# idxSPX <- cumprod(1+retSPX)
# idxUKX <- cumprod(1+retUKX)

# Boucle pour les 1000 prochains jours
for (i in 1:T) {

  # Fenêtre roulante
  ySPX <- logr_SPX_num[i:(i + T - 1)]
  yUKX <- logr_UKX_num[i:(i + T - 1)]

  # VaR à t+1
  VaRSPX[i] <- f_forecast_var(ySPX, 0.95)$VaR_Forecast
  VaRUKX[i] <- f_forecast_var(yUKX, 0.95)$VaR_Forecast
}

dates <- as.Date(index(logr_SPX))
dates_trim  <- dates[T:(T+T-1)]

# Plot des 4 séries
par(mfrow = c(2, 1), mar = c(4, 4, 3, 2))

# Graph SP500
matplot(dates_trim,
        cbind(logr_SPX_num[T:(T+T-1)],VaRSPX),
        type = "l",
        col = c("black", "red"),
        lty = 1, lwd = 1,
        ylab = "VaR Forecast",
        xlab = "",
        main = "VaR forecasts")

legend("topright", legend = c("rendements réalisés", "VaR forecast"),
       col = c("black", "red"), lty = 1, lwd = 1, bty = "n")
# Graph FTSE 100
matplot(dates_trim,
        cbind(logr_UKX_num[T:(T+T-1)], VaRUKX),
        type = "l",
        col = c("black", "red"),
        lty = 1, lwd = 1,
        ylab = "Index (base = 1)",
        xlab = "Date",
        main = "Rendements réalisés")

legend("bottomright", legend = c("rendements réalisés", "VaR forecast"),
       col = c("black", "red"), lty = 1, lwd = 1, bty = "n")

par(mfrow = c(1, 1))
```

